import { Property } from './types';

export const properties: Property[] = [
  {
    id: '1',
    title: 'Luxury Condo at KLCC with Skyline Views',
    price: 1850000,
    pricePerSqft: 1380,
    address: 'Jalan Ampang, KLCC',
    area: 'KLCC',
    state: 'Kuala Lumpur',
    type: 'condo',
    listingType: 'sale',
    bedrooms: 3,
    bathrooms: 3,
    carparks: 2,
    size: 1341,
    imageUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
      'https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?w=800&q=80',
    ],
    agent: {
      name: 'Ahmad Faizal',
      agency: 'ERA Malaysia',
      phone: '+60 12-345 6789',
      avatar: 'https://i.pravatar.cc/150?img=11',
      licenseNo: 'E(1)1234',
    },
    features: ['Swimming Pool', 'Gymnasium', 'Security', '24-Hour Guard', 'Covered Parking', 'Balcony'],
    description: 'Stunning 3-bedroom luxury condominium located in the heart of KLCC. Enjoy breathtaking views of the Petronas Twin Towers from your living room. Features premium finishes throughout with marble flooring, modern kitchen, and spacious bedrooms.',
    isNew: true,
    isFeatured: true,
    isVerified: true,
    postedAt: '2026-05-18',
    tenure: 'Freehold',
    furnishing: 'Fully Furnished',
    floorLevel: 'High Floor (28)',
    builtYear: 2019,
  },
  {
    id: '2',
    title: 'Modern Apartment in Mont Kiara',
    price: 980000,
    pricePerSqft: 820,
    address: 'Jalan Kiara, Mont Kiara',
    area: 'Mont Kiara',
    state: 'Kuala Lumpur',
    type: 'condo',
    listingType: 'sale',
    bedrooms: 2,
    bathrooms: 2,
    carparks: 1,
    size: 1195,
    imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80',
      'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800&q=80',
    ],
    agent: {
      name: 'Priya Nair',
      agency: 'IQI Realty',
      phone: '+60 16-789 0123',
      avatar: 'https://i.pravatar.cc/150?img=5',
      licenseNo: 'E(3)5678',
    },
    features: ['Swimming Pool', 'BBQ Area', 'Wading Pool', 'Gym', 'Intercom', 'CCTV'],
    description: 'Beautifully designed 2-bedroom apartment in the prestigious Mont Kiara enclave. Close to international schools, shopping malls, and dining outlets. Ideal for expats and professionals.',
    isFeatured: true,
    isVerified: true,
    postedAt: '2026-05-15',
    tenure: 'Leasehold',
    furnishing: 'Partially Furnished',
    floorLevel: 'Mid Floor (14)',
    builtYear: 2021,
  },
  {
    id: '3',
    title: 'Spacious Semi-D in Damansara Perdana',
    price: 1650000,
    pricePerSqft: 550,
    address: 'Jalan Damansara, Damansara Perdana',
    area: 'Damansara Perdana',
    state: 'Selangor',
    type: 'house',
    listingType: 'sale',
    bedrooms: 4,
    bathrooms: 4,
    carparks: 3,
    size: 3000,
    imageUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80',
    ],
    agent: {
      name: 'Tan Wei Ming',
      agency: 'PropNex Malaysia',
      phone: '+60 11-2345 6789',
      avatar: 'https://i.pravatar.cc/150?img=3',
      licenseNo: 'E(1)9012',
    },
    features: ['Garden', 'Patio', 'Alarm System', 'Gated Community', 'Covered Porch', 'Wet & Dry Kitchen'],
    description: 'Generous 4-bedroom semi-detached home in a quiet gated community. Tastefully renovated with open-plan living and a private garden. Walking distance to Publika Shopping Gallery.',
    isFeatured: true,
    isVerified: true,
    postedAt: '2026-05-12',
    tenure: 'Freehold',
    furnishing: 'Partially Furnished',
    builtYear: 2015,
  },
  {
    id: '4',
    title: 'Cozy Studio for Rent near Bukit Bintang',
    price: 2200,
    address: 'Jalan Bukit Bintang, Bukit Bintang',
    area: 'Bukit Bintang',
    state: 'Kuala Lumpur',
    type: 'apartment',
    listingType: 'rent',
    bedrooms: 1,
    bathrooms: 1,
    carparks: 1,
    size: 550,
    imageUrl: 'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&q=80',
    ],
    agent: {
      name: 'Sarah Lim',
      agency: 'Hartamas Real Estate',
      phone: '+60 17-456 7890',
      avatar: 'https://i.pravatar.cc/150?img=9',
      licenseNo: 'E(2)3456',
    },
    features: ['Fully Furnished', 'High-Speed WiFi', 'Washing Machine', 'Air-Con', 'Netflix Ready'],
    description: 'Fully furnished studio apartment in the heart of Bukit Bintang. Steps away from Pavilion KL, dining, and entertainment. Perfect for young professionals.',
    isNew: true,
    postedAt: '2026-05-19',
    tenure: 'Leasehold',
    furnishing: 'Fully Furnished',
    floorLevel: 'Low Floor (6)',
    builtYear: 2018,
  },
  {
    id: '5',
    title: '3-Storey Bungalow in Bangsar',
    price: 4200000,
    pricePerSqft: 700,
    address: 'Jalan Bangsar Utama, Bangsar',
    area: 'Bangsar',
    state: 'Kuala Lumpur',
    type: 'bungalow',
    listingType: 'sale',
    bedrooms: 5,
    bathrooms: 6,
    carparks: 4,
    size: 6000,
    imageUrl: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
    ],
    agent: {
      name: 'David Ong',
      agency: 'KW Malaysia',
      phone: '+60 12-678 9012',
      avatar: 'https://i.pravatar.cc/150?img=7',
      licenseNo: 'E(1)7890',
    },
    features: ['Private Pool', 'Garden', 'Home Theatre', 'Smart Home', 'Solar Panels', 'Lift'],
    description: 'Grand 3-storey bungalow set on a 8,000 sqft land in an exclusive Bangsar address. Features a private swimming pool, landscaped garden, and luxurious interiors fit for discerning buyers.',
    isFeatured: true,
    isVerified: true,
    postedAt: '2026-05-10',
    tenure: 'Freehold',
    furnishing: 'Fully Furnished',
    builtYear: 2020,
  },
  {
    id: '6',
    title: 'Commercial Shophouse in Petaling Jaya',
    price: 2800000,
    pricePerSqft: 700,
    address: 'SS2, Petaling Jaya',
    area: 'SS2',
    state: 'Selangor',
    type: 'shophouse',
    listingType: 'sale',
    size: 4000,
    imageUrl: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80',
    ],
    agent: {
      name: 'Michelle Chong',
      agency: 'CBRE WTW',
      phone: '+60 3-7890 1234',
      avatar: 'https://i.pravatar.cc/150?img=20',
      licenseNo: 'E(3)1234',
    },
    features: ['Corner Lot', 'Loading Bay', 'High Ceiling', '3-Phase Power', 'Ample Parking'],
    description: 'Prime 4-storey corner shophouse in the bustling SS2 commercial area. Suitable for F&B, retail, or office use. High foot traffic with excellent road frontage.',
    isVerified: true,
    postedAt: '2026-05-08',
    tenure: 'Freehold',
    builtYear: 2005,
  },
  {
    id: '7',
    title: 'Affordable Condo in Cheras',
    price: 420000,
    pricePerSqft: 420,
    address: 'Jalan Cheras, Cheras',
    area: 'Cheras',
    state: 'Kuala Lumpur',
    type: 'condo',
    listingType: 'sale',
    bedrooms: 3,
    bathrooms: 2,
    carparks: 1,
    size: 1000,
    imageUrl: 'https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&q=80',
    ],
    agent: {
      name: 'Rajan Kumar',
      agency: 'Reapfield Properties',
      phone: '+60 14-234 5678',
      avatar: 'https://i.pravatar.cc/150?img=15',
      licenseNo: 'E(2)6789',
    },
    features: ['Swimming Pool', 'Playground', 'Gym', '24-Hour Security'],
    description: 'Well-maintained 3-bedroom condo in Cheras. Close to MRT station, schools, and wet market. Good rental yield, ideal for first-time buyers.',
    isNew: false,
    postedAt: '2026-05-07',
    tenure: 'Leasehold',
    furnishing: 'Unfurnished',
    floorLevel: 'Mid Floor (10)',
    builtYear: 2014,
  },
  {
    id: '8',
    title: 'Serviced Apartment for Rent in Subang Jaya',
    price: 1800,
    address: 'USJ, Subang Jaya',
    area: 'Subang Jaya',
    state: 'Selangor',
    type: 'apartment',
    listingType: 'rent',
    bedrooms: 2,
    bathrooms: 2,
    carparks: 1,
    size: 850,
    imageUrl: 'https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800&q=80',
    ],
    agent: {
      name: 'Jason Yap',
      agency: 'LaurelCap Sdn Bhd',
      phone: '+60 16-345 6789',
      avatar: 'https://i.pravatar.cc/150?img=12',
      licenseNo: 'E(1)3456',
    },
    features: ['Gym', 'Pool', 'Laundry Room', 'Mini Market', 'Study Room'],
    description: 'Comfortable 2-bedroom serviced apartment near Subang Parade and Giant hypermarket. LRT access nearby makes commuting to KL easy.',
    postedAt: '2026-05-16',
    tenure: 'Leasehold',
    furnishing: 'Fully Furnished',
    floorLevel: 'High Floor (22)',
    builtYear: 2017,
  },
  {
    id: '9',
    title: 'Garden Terrace House in Setia Alam',
    price: 780000,
    pricePerSqft: 390,
    address: 'Setia Alam, Shah Alam',
    area: 'Setia Alam',
    state: 'Selangor',
    type: 'house',
    listingType: 'sale',
    bedrooms: 4,
    bathrooms: 3,
    carparks: 2,
    size: 2000,
    imageUrl: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=80',
    ],
    agent: {
      name: 'Nurul Ain',
      agency: 'S&P Properties',
      phone: '+60 11-5678 9012',
      avatar: 'https://i.pravatar.cc/150?img=25',
      licenseNo: 'E(2)7890',
    },
    features: ['Garden', 'Gated Community', 'Clubhouse', 'Jogging Track', 'Playground'],
    description: 'Brand new 4-bedroom terrace house in the award-winning Setia Alam township. Spacious layout with garden and gated entry. Near schools, hospitals, and AEON Mall.',
    isNew: true,
    isVerified: true,
    postedAt: '2026-05-17',
    tenure: 'Freehold',
    furnishing: 'Unfurnished',
    builtYear: 2025,
  },
  {
    id: '10',
    title: 'Prime Office Space in KLCC',
    price: 12000,
    address: 'Petronas Twin Towers, KLCC',
    area: 'KLCC',
    state: 'Kuala Lumpur',
    type: 'office',
    listingType: 'rent',
    size: 3500,
    imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
    ],
    agent: {
      name: 'Kevin Loh',
      agency: 'Jones Lang LaSalle',
      phone: '+60 3-2888 8888',
      avatar: 'https://i.pravatar.cc/150?img=8',
      licenseNo: 'E(3)8901',
    },
    features: ['Grade A Office', 'Fiber Optic', 'Concierge', 'Meeting Rooms', 'Prayer Room', 'Canteen'],
    description: 'Premium Grade A office space in the iconic KLCC precinct. Entire floor available with panoramic city views. Suitable for MNC or professional firm.',
    isFeatured: true,
    isVerified: true,
    postedAt: '2026-05-05',
    tenure: 'Leasehold',
    builtYear: 2010,
  },
  {
    id: '11',
    title: 'Corner Bungalow Lot in Desa ParkCity',
    price: 3100000,
    pricePerSqft: 620,
    address: 'Desa ParkCity, Kepong',
    area: 'Desa ParkCity',
    state: 'Kuala Lumpur',
    type: 'bungalow',
    listingType: 'sale',
    bedrooms: 5,
    bathrooms: 5,
    carparks: 4,
    size: 5000,
    imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
    ],
    agent: {
      name: 'Alice Tan',
      agency: 'Savills Malaysia',
      phone: '+60 12-901 2345',
      avatar: 'https://i.pravatar.cc/150?img=18',
      licenseNo: 'E(1)2345',
    },
    features: ['Private Pool', 'Smart Home', 'Garden', 'BBQ Area', 'Solar System', 'Alarm System'],
    description: 'Spectacular corner bungalow in the prestigious Desa ParkCity enclave. Surrounded by parks and the man-made lake. Walking distance to the ParkCity mall.',
    isVerified: true,
    postedAt: '2026-05-03',
    tenure: 'Freehold',
    furnishing: 'Partially Furnished',
    builtYear: 2016,
  },
  {
    id: '12',
    title: 'New Launch Condo in Penang Island',
    price: 650000,
    pricePerSqft: 720,
    address: 'Georgetown, Penang',
    area: 'Georgetown',
    state: 'Penang',
    type: 'condo',
    listingType: 'sale',
    bedrooms: 3,
    bathrooms: 2,
    carparks: 2,
    size: 903,
    imageUrl: 'https://images.unsplash.com/photo-1591474200742-8e512e6f98f8?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1591474200742-8e512e6f98f8?w=800&q=80',
    ],
    agent: {
      name: 'Lim Boon Keat',
      agency: 'Penang Realty',
      phone: '+60 4-123 4567',
      avatar: 'https://i.pravatar.cc/150?img=22',
      licenseNo: 'E(4)5678',
    },
    features: ['Sea View', 'Infinity Pool', 'Sky Lounge', 'EV Charging', 'Co-Working Space'],
    description: 'Brand new luxury condo on Penang Island with stunning sea views. Designed for modern living with resort-style facilities. Minutes from Georgetown UNESCO Heritage Zone.',
    isNew: true,
    isFeatured: true,
    isVerified: true,
    postedAt: '2026-05-20',
    tenure: 'Freehold',
    furnishing: 'Unfurnished',
    floorLevel: 'High Floor (32)',
    builtYear: 2027,
  },
  {
    id: '13',
    title: 'Terrace House for Rent in Johor Bahru',
    price: 1500,
    address: 'Taman Daya, Johor Bahru',
    area: 'Johor Bahru',
    state: 'Johor',
    type: 'house',
    listingType: 'rent',
    bedrooms: 3,
    bathrooms: 2,
    carparks: 2,
    size: 1500,
    imageUrl: 'https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=800&q=80',
    ],
    agent: {
      name: 'Hassan Ibrahim',
      agency: 'JB Properties',
      phone: '+60 7-234 5678',
      avatar: 'https://i.pravatar.cc/150?img=14',
      licenseNo: 'E(5)9012',
    },
    features: ['Covered Porch', 'Backyard', 'Near CIQ', 'Good Connectivity'],
    description: 'Neat 3-bedroom intermediate terrace house in Johor Bahru. Great location for those working in Singapore — only 15 mins to Woodlands CIQ.',
    postedAt: '2026-05-14',
    furnishing: 'Partially Furnished',
    builtYear: 2012,
  },
];

export const popularAreas = [
  { name: 'KLCC', state: 'Kuala Lumpur', count: 1240, image: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=400&q=80' },
  { name: 'Mont Kiara', state: 'Kuala Lumpur', count: 876, image: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=400&q=80' },
  { name: 'Bangsar', state: 'Kuala Lumpur', count: 654, image: 'https://images.unsplash.com/photo-1567996070873-62b2c8af5d43?w=400&q=80' },
  { name: 'Petaling Jaya', state: 'Selangor', count: 1890, image: 'https://images.unsplash.com/photo-1600047509358-9dc75507daeb?w=400&q=80' },
  { name: 'Subang Jaya', state: 'Selangor', count: 1120, image: 'https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=400&q=80' },
  { name: 'Georgetown', state: 'Penang', count: 920, image: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=400&q=80' },
];

export function formatPrice(price: number, listingType: 'sale' | 'rent'): string {
  if (listingType === 'rent') {
    return `RM ${price.toLocaleString()}/mo`;
  }
  if (price >= 1000000) {
    return `RM ${(price / 1000000).toFixed(2)}M`;
  }
  return `RM ${price.toLocaleString()}`;
}

export function getPropertiesByType(listingType: 'sale' | 'rent', limit?: number): Property[] {
  const filtered = properties.filter(p => p.listingType === listingType);
  return limit ? filtered.slice(0, limit) : filtered;
}

export function getPropertyById(id: string): Property | undefined {
  return properties.find(p => p.id === id);
}

export function getFeaturedProperties(limit = 6): Property[] {
  return properties.filter(p => p.isFeatured).slice(0, limit);
}
